site_name: Docs / libdebug
site_url: https://docs.libdebug.org
repo_url: https://github.com/libdebug/libdebug
repo_name: libdebug
theme:
  name: material
  logo: assets/libdebug_logo.webp
  favicon: assets/favicon.ico
  palette: 
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: green
      accent: teal
      toggle:
        icon: material/lightbulb 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: dark-green
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
  font:
    text: Nunito
    code: Hack
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate
plugins:
  - search
  - blog
nav:
  - index.md
  - Blog:
    - blog/index.md
    
extra:
  version:
    provider: mike
markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg


extra_css:
  - stylesheets/extra.css