authors:
  team:
    name: The libdebug Team
    description: Maintainers
    avatar: https://libdebug.org/images/libdebug_logo.webp
  io_no:
    name: Io_no
    description: Maintainer
    avatar: https://avatars.githubusercontent.com/u/58036457?v=4
  mrindeciso:
    name: MrIndeciso
    description: Maintainer
    avatar: https://avatars.githubusercontent.com/u/6383492?v=4
  frank01001:
    name: Frank01001
    description: Mainteiner and Documentation Maintainer
    avatar: https://avatars.githubusercontent.com/u/3826161?v=4
  jinblack:
    name: Jinblack
    description: Founder
    avatar: https://avatars.githubusercontent.com/u/58036457?v=4
