# This workflow will install Python dependencies and run tests with multiple versions of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Test Self Hosted

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: [self-hosted, Linux, ARM64]
    timeout-minutes: 15

    steps:
    - uses: actions/checkout@v4

    - name: Activate Virtual Environment
      run: |
        source ~/libdebug-test/bin/activate

    - name: Install library
      run: |
        python -m pip install --upgrade .

    - name: Test with pytest
      run: |
        cd test && python -m pytest --ignore=other_tests
